<a href="https://colab.research.google.com/github/sakrbn/11th-Group/blob/main/Pre_trained_Language_Models_using_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Huggingface](https://huggingface.co/)

In [1]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

In [2]:
sentence = "natural language processing for speech and text data"

In [3]:
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertModel.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [19]:
input = tokenizer(sentence, return_tensors="tf", padding=True,truncation=True)

In [5]:
outputs = model(input)

In [6]:
last_hidden_states = outputs.last_hidden_state

In [8]:
sentence_embedding = tf.reduce_mean(last_hidden_states, axis=1)
sentence_embedding

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-1.36805728e-01, -3.52939293e-02, -2.57828116e-01,
        -1.31376028e-01,  2.54073620e-01,  2.49612287e-01,
         1.83284432e-01,  4.92744923e-01, -2.81577289e-01,
        -2.53174335e-01,  1.25032244e-02, -4.31334222e-04,
        -3.11622441e-01, -2.84044631e-02, -2.52226681e-01,
         5.00769913e-01, -1.52670339e-01,  3.58639568e-01,
        -2.23001912e-01,  4.43309218e-01,  1.22332886e-01,
         2.73647457e-02, -1.42800406e-01,  2.39133760e-01,
         6.68086410e-01, -4.28609788e-01, -3.64565670e-01,
         1.40372336e-01, -5.16278684e-01, -4.61826980e-01,
        -2.28030041e-01,  3.62954319e-01, -2.57070005e-01,
        -1.18888900e-01, -5.86141534e-02,  1.36630714e-01,
        -2.60144591e-01, -2.80792803e-01, -2.99018890e-01,
         2.59279251e-01, -8.24888885e-01, -2.83869088e-01,
        -4.05553430e-01,  6.44517988e-02, -1.13555789e-03,
        -1.92688674e-01, -1.82612166e-01, -3.80586390e-03,
      

In [20]:
sentence_embedding.numpy

<function Tensor.numpy>

In [21]:
sentence_embedding.shape

torch.Size([1, 768])

In [22]:
import torch
from transformers import BertModel

In [12]:
model = BertModel.from_pretrained(model_name)

In [13]:
inputs = tokenizer(sentence, return_tensors="pt", padding=True,truncation=True)

In [14]:
with torch.no_grad():
    outputs = model(**inputs)

In [15]:
last_hidden_states = outputs.last_hidden_state

In [16]:
sentence_embedding = torch.mean(last_hidden_states, dim=1)

In [17]:
sentence_embedding.shape

torch.Size([1, 768])

In [18]:
sentence_embedding

tensor([[-1.3681e-01, -3.5294e-02, -2.5783e-01, -1.3138e-01,  2.5407e-01,
          2.4961e-01,  1.8328e-01,  4.9275e-01, -2.8158e-01, -2.5317e-01,
          1.2503e-02, -4.3064e-04, -3.1162e-01, -2.8405e-02, -2.5223e-01,
          5.0077e-01, -1.5267e-01,  3.5864e-01, -2.2300e-01,  4.4331e-01,
          1.2233e-01,  2.7365e-02, -1.4280e-01,  2.3913e-01,  6.6809e-01,
         -4.2861e-01, -3.6457e-01,  1.4037e-01, -5.1628e-01, -4.6183e-01,
         -2.2803e-01,  3.6295e-01, -2.5707e-01, -1.1889e-01, -5.8614e-02,
          1.3663e-01, -2.6014e-01, -2.8079e-01, -2.9902e-01,  2.5928e-01,
         -8.2489e-01, -2.8387e-01, -4.0555e-01,  6.4452e-02, -1.1353e-03,
         -1.9269e-01, -1.8261e-01, -3.8062e-03,  7.7143e-03,  3.0249e-01,
         -7.4040e-01,  2.0622e-01, -1.4026e-01,  2.2627e-01,  9.7099e-02,
          6.4996e-01,  4.4649e-03, -6.6440e-01,  3.3527e-01, -1.6868e-01,
          2.0501e-01, -1.1281e-01, -2.2569e-01, -6.0236e-01,  7.3980e-01,
         -4.1785e-01, -1.2817e-01, -1.